[package]
name = "llvm-js-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compiler = { workspace = true }
ast = { workspace = true }
thiserror = { workspace = true }

clap = { version = "4.1.1", features = ["derive"] }
