[package]
name = "rust_core"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#crate-type = ["staticlib"]

[dependencies]
proptest = { workspace = true }
test-strategy = { workspace = true }
