name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    strategy:
      matrix:
        # TODO fix macos-latest and windows-latest build
        os: [ubuntu-latest, macos-latest]
        toolchain: [stable]
        mode: ["", "--release"]
        include:
          - os: ubuntu-latest
            toolchain: nightly
            experimental: true

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    # - name: Install LLVM
    #   uses: Mr-Leshiy/install-llvm-action@master
    #   with:
    #     version: "14.0"
    - name: Install LLVM
      run: |
        git clone https://github.com/llvm/llvm-project.git
        cd llvm-project
        git checkout release/14.x
        mkdir build
        cmake -S llvm -B build -DCMAKE_BUILD_TYPE=Release
        cd build
        make -j
        sudo make install

    - if: ${{ matrix.os == 'macos-latest' }}
      name: Setup default clang
      run: xcode-select --install

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-targets ${{ matrix.mode }} ${{ matrix.features }}

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: ${{ matrix.mode }} ${{ matrix.features }}

  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt
          override: true

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
          override: true

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

