name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1.5.4
      with:
        version: "14.0"

    - name: Build cpp lib 
      run: |
        cmake . -Bbuild
        cmake --build build --parallel 2

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-targets

    - name: Install nextest
      run: cargo install cargo-nextest --locked

    - name: Run tests
      run: cargo nextest run

  mem-check:
    name: Memory check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1.5.4
      with:
        version: "14.0"

    - name: Install Valgrind
      run: sudo apt-get install valgrind
    
    - name: Build cpp lib 
      run: |
        cmake . -Bbuild
        cmake --build build --parallel 2

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-targets

    - name: Install nextest
      run: cargo install cargo-nextest --locked

    - name: Run tests
      run: cargo nextest run memory_tests --features mem-check


  fmt:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt, clippy
          override: true

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          toolchain: stable
          command: clippy
          args: --all-targets --all-features -- -D warnings
