name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    needs: Clippy
    strategy:
      matrix:
        # TODO fix macos-latest and windows-latest build
        os: [ubuntu-latest, macos-latest]
        toolchain: [stable]
        mode: ["", "--release"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1.5.4
      with:
        version: "14.0"

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-targets ${{ matrix.mode }}

    - name: Install nextest
      run: cargo install cargo-nextest --locked
    - if: ${{ runner.os == 'ubuntu-latest' }}
      name: Run tests
      run: cargo nextest run

mem-check:
    name: Memory check
    needs: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1.5.4
      with:
        version: "14.0"

    - name: Install Valgrind
      run: apt-get install valgrind

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-targets

    - name: Install nextest
      run: cargo install cargo-nextest --locked
    - name: Run tests
      run: cargo nextest run memory_tests --features mem-check


  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt
          override: true

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  clippy:
    name: Clippy
    needs: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
          override: true

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings
